// Pre-populate with ALL Une Femme emails from comprehensive plan
const uneFemmeEmails = [
  // PRE-ENGAGEMENT EMAILS (UF-001 to UF-008)
  ["Pre-Engagement", "Kickoff", "High", "Matt", "Zach Pelka", "jameca", new Date(2025, 5, 9), "HARD", "Une Femme AI Program: Confirming Thursday's Discussion + Next Steps", "Subject: Une Femme AI Program: Confirming Thursday's Discussion + Next Steps\n\nHi Zach,\n\nThank you for making time Thursday to finalize our program approach...", "", "", "Subject: Une Femme AI Program: Confirming Thursday's Discussion + Next Steps\n\nHi Zach,\n\nThank you for making time Thursday to finalize our program approach. Your commitment to maintaining operational excellence while scaling to 600k+ cases is exactly where AI can make an immediate impact.\n\nTo confirm our discussion:\n✓ 8-week accelerated timeline (June 16 - August 8, 2025)\n✓ 4-phase approach with Week 2 intensive sprint\n✓ 11 participants across executive and team training\n✓ Focus areas: RNDC execution, demand forecasting, brand evolution\n✓ Investment: $[X] + platform costs ($220-550/month)\n\nImmediate actions needed by Friday, June 13, 2025:\n1. Review attached SOW and confirm via ZohoSign\n2. Verify team groupings (attached spreadsheet)\n3. Confirm Sam's performance metrics for at-risk component\n4. Approve IT security requirements for AI platforms\n\nI'll send calendar holds for all Week 1-2 sessions within 24 hours of SOW signature.\n\nLooking forward to partnering with Une Femme on this transformation.\n\nBest,\nMatt", "Ready"],
  
  ["Pre-Engagement", "Deliverable", "High", "Jameca", "Zach Pelka", "matt, sara", new Date(2025, 5, 9), "HARD", "[Action Required] Une Femme AI Program: Complete Documentation Package", "Subject: [Action Required] Une Femme AI Program: Complete Documentation Package\n\nHi Zach,\n\nAs promised, here's the complete documentation package...", "", "", "Subject: [Action Required] Une Femme AI Program: Complete Documentation Package\n\nHi Zach,\n\nAs promised, here's the complete documentation package for your AI transformation program:\n\n📎 Attached Documents:\n1. Modified SOW with 4-phase approach (DocuSign ready)\n2. Detailed Week 1-2 Schedule (please verify executive availability)\n3. Team Groupings Spreadsheet (confirm or suggest changes)\n4. AI Platform Requirements & Security Overview\n5. Invoice for initial payment\n6. Intake forms for all 12 participants\n\n🎯 Actions needed by EOD Friday, June 13, 2025:\n□ Sign SOW via ZohoSign\n□ Confirm team groupings or request changes\n□ Forward platform requirements to IT for approval\n□ Distribute intake forms to all participants\n□ Approve invoice for finance processing\n\n📅 Once confirmed, you'll receive:\n- Calendar invitations for all sessions\n- Platform setup instructions for 11 users\n- Welcome packet for participants\n- Slack channel invitation\n\nQuestions on any documents? Happy to jump on a quick call.\n\nBest,\nJameca\n\nP.S. - I've included Sara's email for invoice processing. Let me know if finance needs any additional documentation.", "Ready"],
  
  ["Pre-Engagement", "Scheduling", "Medium", "Jameca", "Zach Pelka", "", new Date(2025, 5, 9), "HARD", "Quick Confirmation: Training Group Assignments for Une Femme Team", "Subject: Quick Confirmation: Training Group Assignments for Une Femme Team\n\nHi Zach,\n\nBased on our discussion, I've organized the training participants...", "", "", "Subject: Quick Confirmation: Training Group Assignments for Une Femme Team\n\nHi Zach,\n\nBased on our discussion, I've organized the training participants into two functional groups. Please confirm these work with team schedules and dynamics:\n\n**Group 1: Operations/Compliance Focus** (Thursdays 5-6:30pm EST)\n• Evyn Cameron - Winemaking\n• Micha Carter - Compliance  \n• Sara Soares - Finance\n• [New VA - name needed]\n\n**Group 2: Sales/Marketing Focus** (Fridays 1-2:30pm EST)\n• Whitney Wright - Communications\n• Joe Taverrite - National Accounts\n• Kait Skye - Trade Marketing\n• Kimberly Pettit - TX Sales\n\nConsiderations:\n- Groups are intentionally cross-functional for knowledge sharing\n- Times selected to avoid typical wine industry conflicts\n- Can shuffle if someone has a standing conflict\n\nPlease confirm by responding with:\n1. ✓ Groups look good, or\n2. Requested changes\n\nThanks!\nJameca", "Ready"],
  
  ["Pre-Engagement", "Scheduling", "High", "Jameca", "Jen Pelka, Zach Pelka, Sam Barnes, Thomas Hartman", "matt", new Date(2025, 5, 9), "HARD", "[Executive Team] Please Block: AI Strategy Sessions Week of June 16", "Subject: [Executive Team] Please Block: AI Strategy Sessions Week of June 16\n\nExecutive Team,\n\nAs we prepare for the AI program launch...", "", "", "Subject: [Executive Team] Please Block: AI Strategy Sessions Week of June 16\n\nExecutive Team,\n\nAs we prepare for the AI program launch, Jameca will conduct 45-minute strategy sessions with each of you during Week 1, with Matt or Aaron joining along.\n\n**Book Your Strategy Session:**\n\n🗓️ Click here to schedule: [Calendly Link]\n\nAvailable times (EST):\n• Tuesday-Friday, June 17-20, 2025\n• Morning slots: 10:00am-12:00pm EST\n• Afternoon slots: 2:00pm-5:00pm EST\n\nSession duration: 45 minutes\n\nThese sessions will explore:\n- Your biggest scaling challenges\n- Where AI can deliver immediate ROI\n- Building your personal AI assistant\n\nPlease book your preferred time by EOD tomorrow. You'll receive an automatic calendar invitation upon booking.\n\nBest,\nJameca\n\nP.S. - Sam, we'll specifically focus on how AI can accelerate key account expansion using the Delta model.", "Ready"],
  
  ["Pre-Engagement", "Platform Setup", "High", "Alex", "Zach Pelka", "matt, jameca", new Date(2025, 5, 9), "HARD", "IT Setup Required: AI Platforms for 11 Une Femme Users", "Subject: IT Setup Required: AI Platforms for 11 Une Femme Users\n\nHi Zach,\n\nTo ensure smooth platform access for all participants...", "", "", "Subject: IT Setup Required: AI Platforms for 11 Une Femme Users\n\nHi Zach,\n\nTo ensure smooth platform access for all participants, we need IT approval for the following:\n\n**Required Platforms:**\n1. ChatGPT Teams ($25/user/month x 11 users = $275/month)\n   - Uses SSO with Une Femme email addresses\n   - Requires domain verification\n   \n2. Claude Teams ($25/user/month x 11 users = $275/month)\n   - Separate login per user\n   - No domain verification needed\n\n**IT Actions Needed by Friday, June 20, 2025:**\n1. Approve domain for ChatGPT Teams\n2. Whitelist both platforms in firewall/security tools\n3. Confirm no VPN conflicts for access\n4. Authorize recurring payment setup\n\n**Timeline:** Users need access by Monday, June 23, 2025 (Week 2 start)\n\nAttached: Platform security documentation\n\n**Need help? Book a quick call:**\n🗓️ Schedule IT consultation: [Calendly Link]\nAvailable times: Mon-Fri 9am-5pm EST (15-minute slots)\n\nThanks,\nAlex", "Ready"],
  
  ["Pre-Engagement", "Contract", "Medium", "Sheera", "Sara Soares", "zach, matt", new Date(2025, 5, 9), "FLEX", "Une Femme AI Program: Invoice #1247 for Initial Payment", "Subject: Une Femme AI Program: Invoice #1247 for Initial Payment\n\nHi Sara,\n\nPer Zach's approval, please find attached Invoice #1247...", "", "", "Subject: Une Femme AI Program: Invoice #1247 for Initial Payment\n\nHi Sara,\n\nPer Zach's approval, please find attached Invoice #1247 for the AI transformation program:\n\n**Invoice Details:**\n- Amount: $[X] (initial payment)\n- Terms: Net 30\n- Project: 8-week AI Program\n- Period: June 16 - August 8, 2025\n\n**Payment Schedule:**\n- Initial payment: Upon SOW signature\n- Final payment: Upon completion (pending performance metrics)\n- Platform costs: Monthly billing (~$550/month)\n\nPlease confirm receipt and expected payment date. We typically see ACH within 7-10 business days.\n\nLet me know if you need any additional documentation for processing.\n\nBest,\nSheera\n\nP.S. - Congrats on maintaining that 99.8% forecast accuracy! Looking forward to supporting this exciting initiative.", "Ready"],
  
  ["Pre-Engagement", "Other", "Medium", "Jameca", "All Team", "matt", new Date(2025, 5, 9), "FLEX", "Welcome to Une Femme's AI Transformation Journey!", "Subject: Welcome to Une Femme's AI Transformation Journey!\n\nTeam Une Femme,\n\nCongratulations on being selected for this groundbreaking AI program...", "", "", "Subject: Welcome to Une Femme's AI Transformation Journey!\n\nTeam Une Femme,\n\nCongratulations on being selected for this groundbreaking AI program! Over the next 8 weeks, you'll develop skills that help Une Femme scale intelligently to 600k+ cases and beyond.\n\n**Your Pre-Launch Checklist:**\n□ Complete intake form (link below) by Friday, June 20, 2025\n□ Block calendar for your assigned sessions\n□ Watch 5-min welcome video from Matt\n□ Join Slack channel (invitation coming separately)\n\n**Complete Your Intake Form:** [TypeForm Link]\nTime required: 8 minutes\n\nThis helps us customize training to your specific role and challenges.\n\n**What to Expect:**\n- Week 1: Discovery and assessment\n- Week 2: Intensive launch (all programs start!)\n- Weeks 3-7: Skill building and implementation\n- Week 8: Celebration and future planning\n\nQuestions? I'm here to help make this transformative for you and Une Femme.\n\nWelcome aboard!\n\nJameca Patrick\nClient Success Lead, Happy Robots\n\nP.S. - Jen and Zach's vision for AI at Une Femme is inspiring. You're part of something special.", "Ready"],
  
  ["Pre-Engagement", "Platform Setup", "Low", "Alex", "All Team", "", new Date(2025, 5, 9), "FLEX", "[Slack Invite] Join #unefemme-ai-program Channel", "Subject: [Slack Invite] Join #unefemme-ai-program Channel\n\nHi everyone,\n\nYour dedicated Slack channel is ready...", "", "", "Subject: [Slack Invite] Join #unefemme-ai-program Channel\n\nHi everyone,\n\nYour dedicated Slack channel is ready! This will be our quick-communication hub throughout the program.\n\n**Click to Join:** [Slack invitation link]\n\n**Channel: #unefemme-ai-program**\n\nWhat we'll use Slack for:\n• Quick questions between sessions\n• Sharing wins and breakthroughs\n• Technical support\n• Resource sharing\n• Daily inspirations and tips\n\nFirst post: Introduce yourself and share one thing you hope AI helps you accomplish.\n\nSee you there!\n\nAlex", "Ready"],
  
  // WEEK 1: IDENTIFY PHASE EMAILS (UF-009 to UF-019)
  ["Week 1", "Other", "High", "Jameca", "All Team", "", new Date(2025, 5, 16), "FLEX", "[Starting in 2 Hours] Une Femme AI Kickoff - Ready to Transform?", "Subject: [Starting in 2 Hours] Une Femme AI Kickoff - Ready to Transform?\n\nGood morning, Team!\n\nOur AI transformation journey begins in 2 hours...", "", "", "Subject: [Starting in 2 Hours] Une Femme AI Kickoff - Ready to Transform?\n\nGood morning, Team!\n\nOur AI transformation journey begins in 2 hours! Here's everything you need:\n\n📅 **Today: Monday, June 16, 2025 @ 2:00pm EST**\n🔗 **Zoom Link:** [Click here to join]\n⏱️ **Duration:** 60 minutes\n\n**Pre-Kickoff Checklist:**\n✓ Test your Zoom connection\n✓ Have your intake form insights handy\n✓ Grab your favorite beverage\n✓ Bring your questions and excitement!\n\n**What We'll Cover:**\n• Why AI matters for scaling to 600k+ cases\n• Our 4-phase journey together\n• Week 1-2 intensive schedule\n• Quick wins we'll achieve together\n\nCan't make it? Recording will be available, but live participation is highly encouraged for Q&A.\n\nSee you soon!\n\nJameca\n\nP.S. - Jen has a special message about why she's betting on AI for Une Femme's future.", "Draft"],
  
  ["Week 1", "Other", "High", "Jameca", "Jen Pelka", "aaron", new Date(2025, 5, 17), "HARD", "[Calendar] Your AI Strategy Session - Tuesday at 1pm EST", "Subject: [Calendar] Your AI Strategy Session - Tuesday at 1pm EST\n\nHi Jen,\n\nConfirming your AI strategy session with Jameca...", "", "", "Subject: [Calendar] Your AI Strategy Session - Tuesday at 1pm EST\n\nHi Jen,\n\nConfirming your AI strategy session with Jameca (Matt/Aaron will join as note-taker):\n\n📅 Date: Tuesday, June 17, 2025\n⏰ Time: 1:00-1:45pm EST  \n🔗 Zoom: [Personal meeting room]\n📎 Pre-read: None required\n\n**Our 45-Minute Agenda:**\n1. Your biggest obstacles to reaching 600k cases (15 min)\n2. Where AI can eliminate friction in your workflow (15 min)\n3. Building your personal AI assistant (10 min)\n4. Quick wins for Q1 implementation (5 min)\n\n**Personalized preparation thought:** Consider how AI could accelerate the \"serious to fun\" brand evolution.\n\nLooking forward to our conversation.\n\nBest,\nJameca", "Draft"],
  
  ["Week 1", "Other", "High", "Jameca", "Zach Pelka", "aaron", new Date(2025, 5, 18), "HARD", "[Calendar] Your AI Strategy Session - Wednesday at 2pm EST", "Subject: [Calendar] Your AI Strategy Session - Wednesday at 2pm EST\n\nHi Zach,\n\nConfirming your AI strategy session with Jameca...", "", "", "Subject: [Calendar] Your AI Strategy Session - Wednesday at 2pm EST\n\nHi Zach,\n\nConfirming your AI strategy session with Jameca (Matt/Aaron will join as note-taker):\n\n📅 Date: Wednesday, June 18, 2025\n⏰ Time: 2:00-2:45pm EST  \n🔗 Zoom: [Personal meeting room]\n📎 Pre-read: None required\n\n**Our 45-Minute Agenda:**\n1. Your biggest obstacles to reaching 600k cases (15 min)\n2. Where AI can eliminate friction in your workflow (15 min)\n3. Building your personal AI assistant (10 min)\n4. Quick wins for Q1 implementation (5 min)\n\n**Personalized preparation thought:** Think about your top 3 RNDC execution frustrations.\n\nLooking forward to our conversation.\n\nBest,\nJameca", "Draft"],
  
  ["Week 1", "Other", "High", "Jameca", "Sam Barnes", "aaron", new Date(2025, 5, 19), "HARD", "[Calendar] Your AI Strategy Session - Thursday at 11am EST", "Subject: [Calendar] Your AI Strategy Session - Thursday at 11am EST\n\nHi Sam,\n\nConfirming your AI strategy session with Jameca...", "", "", "Subject: [Calendar] Your AI Strategy Session - Thursday at 11am EST\n\nHi Sam,\n\nConfirming your AI strategy session with Jameca (Matt/Aaron will join as note-taker):\n\n📅 Date: Thursday, June 19, 2025\n⏰ Time: 11:00-11:45am EST  \n🔗 Zoom: [Personal meeting room]\n📎 Pre-read: None required\n\n**Our 45-Minute Agenda:**\n1. Your biggest obstacles to reaching 600k cases (15 min)\n2. Where AI can eliminate friction in your workflow (15 min)\n3. Building your personal AI assistant (10 min)\n4. Quick wins for Q1 implementation (5 min)\n\n**Personalized preparation thought:** What if you could replicate the Delta success 10x faster?\n\nLooking forward to our conversation.\n\nBest,\nJameca", "Draft"],
  
  ["Week 1", "Other", "High", "Jameca", "Thomas Hartman", "aaron", new Date(2025, 5, 20), "HARD", "[Calendar] Your AI Strategy Session - Friday at 3pm EST", "Subject: [Calendar] Your AI Strategy Session - Friday at 3pm EST\n\nHi Thomas,\n\nConfirming your AI strategy session with Jameca...", "", "", "Subject: [Calendar] Your AI Strategy Session - Friday at 3pm EST\n\nHi Thomas,\n\nConfirming your AI strategy session with Jameca (Matt/Aaron will join as note-taker):\n\n📅 Date: Friday, June 20, 2025\n⏰ Time: 3:00-3:45pm EST  \n🔗 Zoom: [Personal meeting room]\n📎 Pre-read: None required\n\n**Our 45-Minute Agenda:**\n1. Your biggest obstacles to reaching 600k cases (15 min)\n2. Where AI can eliminate friction in your workflow (15 min)\n3. Building your personal AI assistant (10 min)\n4. Quick wins for Q1 implementation (5 min)\n\n**Personalized preparation thought:** Where does JIT manufacturing hit capacity constraints?\n\nLooking forward to our conversation.\n\nBest,\nJameca", "Draft"],
  
  ["Week 1", "Survey", "High", "Jameca", "All Team", "", new Date(2025, 5, 17), "HARD", "🍷 Your Input Shapes Une Femme's AI Future (10 min survey)", "Subject: 🍷 Your Input Shapes Une Femme's AI Future (10 min survey)\n\nHi Team,\n\nYesterday's kickoff energy was fantastic! Now we need your insights...", "", "", "Subject: 🍷 Your Input Shapes Une Femme's AI Future (10 min survey)\n\nHi Team,\n\nYesterday's kickoff energy was fantastic! Now we need your insights to build the RIGHT AI solutions for Une Femme.\n\n**Take the Survey Now:** [TypeForm Link]\n⏱️ Time: 10 minutes\n📅 Deadline: Thursday, June 19, 2025, 8pm EST\n\n**Why Your Input Matters:**\nYour responses directly determine which AI tools we build first. Be candid about your challenges - this is your chance to shape solutions.\n\n**We're Especially Interested In:**\n• RNDC execution pain points\n• Demand forecasting challenges\n• Brand content bottlenecks\n• Compliance automation opportunities\n• Your personal workflow friction\n\nAll responses are confidential and will be presented in aggregate.\n\nThanks for investing 10 minutes in Une Femme's AI future!\n\nJameca\n\nP.S. - First 5 responses get a Happy Robots swag box! 📦", "Draft"],
  
  ["Week 1", "Other", "Medium", "Jameca", "Micha Carter", "", new Date(2025, 5, 18), "FLEX", "⏰ 24 Hours Left: Une Femme AI Survey Closes Tomorrow", "Subject: ⏰ 24 Hours Left: Une Femme AI Survey Closes Tomorrow\n\nHi Micha,\n\nQuick reminder - we need your insights to build the right AI solutions...", "", "", "Subject: ⏰ 24 Hours Left: Une Femme AI Survey Closes Tomorrow\n\nHi Micha,\n\nQuick reminder - we need your insights to build the right AI solutions for Une Femme!\n\n**Survey Status:**\n✅ 7 of 12 responses received\n⏳ Your response: Not yet received\n📅 Deadline: Tomorrow (Thursday, June 19) 8pm EST\n\n**Take Survey Now:** [TypeForm Link]\nTime needed: Just 10 minutes\n\nYour unique perspective on multi-state compliance and TTB reporting is crucial for our analysis.\n\nQuestions? Reply here or ping me on Slack.\n\nThanks!\nJameca", "Draft"],
  
  ["Week 1", "Other", "Medium", "Jameca", "Joe Taverrite", "", new Date(2025, 5, 18), "FLEX", "⏰ 24 Hours Left: Une Femme AI Survey Closes Tomorrow", "Subject: ⏰ 24 Hours Left: Une Femme AI Survey Closes Tomorrow\n\nHi Joe,\n\nQuick reminder - we need your insights to build the right AI solutions...", "", "", "Subject: ⏰ 24 Hours Left: Une Femme AI Survey Closes Tomorrow\n\nHi Joe,\n\nQuick reminder - we need your insights to build the right AI solutions for Une Femme!\n\n**Survey Status:**\n✅ 7 of 12 responses received\n⏳ Your response: Not yet received\n📅 Deadline: Tomorrow (Thursday, June 19) 8pm EST\n\n**Take Survey Now:** [TypeForm Link]\nTime needed: Just 10 minutes\n\nYour unique perspective on managing key partnerships like Delta, Marriott, and Disney is crucial for our analysis.\n\nQuestions? Reply here or ping me on Slack.\n\nThanks!\nJameca", "Draft"],
  
  ["Week 1", "Other", "High", "Matt", "Whitney Wright", "", new Date(2025, 5, 19), "HARD", "[FINAL HOURS] Your voice matters - Une Femme AI Survey", "Subject: [FINAL HOURS] Your voice matters - Une Femme AI Survey\n\nHi Whitney,\n\nI know you're busy, but your input is critical...", "", "", "Subject: [FINAL HOURS] Your voice matters - Une Femme AI Survey\n\nHi Whitney,\n\nI know you're busy, but your input is critical for Une Femme's AI success.\n\nWe're at 10 of 12 responses - yours is one of the two we're missing.\n\n**Take it now:** [TypeForm Link]\nEven 5 minutes of partial responses helps.\n\nYour insights on communications and brand positioning directly shape what we build in next week's sprint.\n\nCan you help us hit 100% participation?\n\nMatt", "Draft"],
  
  ["Week 1", "Other", "Low", "Jameca", "Executives", "matt or aaron", new Date(2025, 5, 20), "FLEX", "Thank You + Key Takeaways from Our AI Strategy Session", "Subject: Thank You + Key Takeaways from Our AI Strategy Session\n\nHi [Executive],\n\nThank you for the candid conversation yesterday...", "", "", "Subject: Thank You + Key Takeaways from Our AI Strategy Session\n\nHi [Executive],\n\nThank you for the candid conversation yesterday. Your insights on [specific topic] were particularly valuable.\n\n**Key Takeaways I Captured:**\n• Main challenge: [Specific challenge discussed]\n• Highest-impact AI opportunity: [Opportunity identified]\n• Quick win target: [Specific quick win]\n• Success metric: [How we'll measure success]\n\nThese insights will directly inform:\n1. Monday's findings presentation\n2. Week 2 sprint focus\n3. Your custom GPT development\n\nI'll incorporate these into our recommendations and look forward to building solutions that address your specific needs.\n\nBest,\nJameca\n\nP.S. - [Personalized comment about something they mentioned]", "Draft"],
  
  ["Week 1", "Status Update", "Medium", "Matt", "Zach Pelka", "", new Date(2025, 5, 19), "FLEX", "[Week 1 Update] Une Femme AI Program: On Track", "Subject: [Week 1 Update] Une Femme AI Program: On Track\n\nHi Zach,\n\nQuick Thursday update on our Week 1 discovery...", "", "", "Subject: [Week 1 Update] Une Femme AI Program: On Track\n\nHi Zach,\n\nQuick Thursday update on our Week 1 discovery:\n\n**Completed:**\n✅ Kickoff meeting: 12/12 attended (great energy!)\n✅ Executive interviews: 4/4 complete (Jameca led with note-taker support)\n✅ Survey responses: 11/12 (following up with final person)\n✅ Platform requirements: Sent to IT team\n\n**Key Themes Emerging:**\n1. RNDC execution is universal pain point\n2. Strong interest in demand forecasting automation\n3. Brand content needs as you shift to \"fun\"\n4. Compliance automation could save 15+ hours/week\n\n**Week 2 Prep Status:**\n• Sprint recommendation: RNDC scorecard automation\n• All session times confirmed\n• Platform access being processed\n• Team excitement level: High\n\nAny concerns? None currently.\n\nWe're set for Monday's findings presentation at 9am. See you then!\n\nMatt", "Draft"],
  
  ["Week 1", "Other", "High", "Jameca", "All Team", "", new Date(2025, 5, 20), "HARD", "[Action Required] Prepare for Monday's AI Launch - 3 Quick Steps", "Subject: [Action Required] Prepare for Monday's AI Launch - 3 Quick Steps\n\nTeam,\n\nIncredible Week 1! Your insights are shaping an exciting Week 2...", "", "", "Subject: [Action Required] Prepare for Monday's AI Launch - 3 Quick Steps\n\nTeam,\n\nIncredible Week 1! Your insights are shaping an exciting Week 2. Here's what you need to do before Monday:\n\n**3 Actions Before Monday:**\n\n1️⃣ **Verify Platform Access** (5 min)\n   - Check email for ChatGPT Teams invitation\n   - Check email for Claude Teams invitation  \n   - Accept both and set passwords\n   - Reply \"✓ Platforms ready\" when complete\n\n2️⃣ **Block Your Calendar**\n   - Your full Week 2 schedule is attached\n   - Add all sessions to your calendar now\n   - Treat these as unmovable commitments\n\n3️⃣ **Complete Pre-Work** (10 min)\n   - Watch \"AI Basics for Wine Industry\" video [Link]\n   - Review attached one-pager on computational thinking\n   - Come with one specific workflow you want to automate\n\n**Critical Sessions Monday:**\n• 9:00am - Executive findings (executives only)\n• 1:00pm - Sprint planning (Zach + sprint team)\n• 2:00pm - All-team launch (everyone!)\n\nQuestions? I'm monitoring Slack all weekend.\n\nLet's make Week 2 transformative!\n\nJameca", "Draft"],
  
  // WEEK 2: INTENSIVE LAUNCH WEEK (UF-020 to UF-029)
  ["Week 2", "Other", "High", "Matt", "All Team", "", new Date(2025, 5, 23), "FLEX", "🚀 LAUNCH DAY: Your AI Transformation Begins Now!", "Subject: 🚀 LAUNCH DAY: Your AI Transformation Begins Now!\n\nGood morning, Une Femme AI Pioneers!\n\nToday we make the leap from planning to building...", "", "", "Subject: 🚀 LAUNCH DAY: Your AI Transformation Begins Now!\n\nGood morning, Une Femme AI Pioneers!\n\nToday we make the leap from planning to building. By Friday, you'll have working AI tools improving your daily workflow.\n\n**Today's Schedule:**\n• 9:00am - Executive findings reveal top opportunities\n• 1:00pm - Sprint team designs your RNDC solution  \n• 2:00pm - ALL HANDS: Training launches, platforms activate\n\n**Your Launch Checklist:**\n□ Platforms ready? (Check now - we need 100%)\n□ Calendar blocked? (This week is intensive)\n□ Mindset ready? (Growth mode: ON)\n\n**Week 2 Promise:**\nBy Friday, you'll have:\n✓ Working AI tool solving real Une Femme challenge\n✓ Personal AI assistant configuration started\n✓ New skills you can apply immediately\n\nLet's build something amazing together!\n\nMatt", "Draft"],
  
  ["Week 2", "Other", "High", "Jameca", "Executives", "", new Date(2025, 5, 23), "FLEX", "[Starting in 30 min] Executive AI Findings - Link Inside", "Subject: [Starting in 30 min] Executive AI Findings - Link Inside\n\nHi Executives,\n\nYour session starts in 30 minutes...", "", "", "Subject: [Starting in 30 min] Executive AI Findings - Link Inside\n\nHi Executives,\n\nYour session starts in 30 minutes!\n\n**Session: Executive AI Findings Presentation**\n⏰ Time: 12:00-12:45pm EST\n🔗 Zoom: [Click to join]\n📊 Materials: Will be shared on screen\n\n**What to Bring:**\n• Questions about the findings\n• Input on sprint priorities\n• Decision-making authority (we're choosing what to build)\n\nCan't make it? Please let me know ASAP for recording access.\n\nSee you soon!\n\nJameca", "Draft"],
  
  ["Week 2", "Other", "High", "Jameca", "Sprint Team", "", new Date(2025, 5, 23), "FLEX", "[Starting in 30 min] AI Sprint Planning - Link Inside", "Subject: [Starting in 30 min] AI Sprint Planning - Link Inside\n\nHi Sprint Team,\n\nYour session starts in 30 minutes...", "", "", "Subject: [Starting in 30 min] AI Sprint Planning - Link Inside\n\nHi Sprint Team,\n\nYour session starts in 30 minutes!\n\n**Session: AI Sprint Planning**\n⏰ Time: 4:00-5:00pm EST\n🔗 Zoom: [Click to join]\n Miro Board: [Link to board]\n\n**What to Bring:**\n• Your top RNDC pain points\n• Ideas for automation\n• A collaborative mindset!\n\nCan't make it? Please let me know ASAP.\n\nSee you soon!\n\nJameca", "Draft"],
  
  ["Week 2", "Other", "High", "Jameca", "All Team", "", new Date(2025, 5, 23), "FLEX", "[Starting in 30 min] All-Team AI Launch - Link Inside", "Subject: [Starting in 30 min] All-Team AI Launch - Link Inside\n\nHi Team,\n\nOur big launch session starts in 30 minutes...", "", "", "Subject: [Starting in 30 min] All-Team AI Launch - Link Inside\n\nHi Team,\n\nOur big launch session starts in 30 minutes!\n\n**Session: All-Team AI Launch**\n⏰ Time: 5:00-6:00pm EST\n🔗 Zoom: [Click to join]\n\n**What to Bring:**\n• Your platform logins (test them now!)\n• Your biggest question about AI\n• Excitement to learn!\n\nCan't make it? Please let me know ASAP for recording access.\n\nSee you soon!\n\nJameca", "Draft"],
  
  ["Week 2", "Other", "High", "Jameca", "Group 1", "", new Date(2025, 5, 24), "FLEX", "[Starting in 30 min] AI Training - Group 1 - Link Inside", "Subject: [Starting in 30 min] AI Training - Group 1 - Link Inside\n\nHi Group 1,\n\nYour first AI training session starts in 30 minutes...", "", "", "Subject: [Starting in 30 min] AI Training - Group 1 - Link Inside\n\nHi Group 1,\n\nYour first AI training session starts in 30 minutes!\n\n**Session: Module 1 - AI Foundations**\n⏰ Time: 5:00-6:30pm EST\n🔗 Zoom: [Click to join]\n\n**What to Bring:**\n• Your platform logins\n• One workflow you want to automate\n• All your questions!\n\nCan't make it? Please let me know ASAP.\n\nSee you soon!\n\nJameca", "Draft"],
  
  ["Week 2", "Platform Setup", "High", "Alex", "Evyn Cameron", "", new Date(2025, 5, 24), "HARD", "⚡ Quick Fix: AI Platform Access Issues", "Subject: ⚡ Quick Fix: AI Platform Access Issues\n\nHi Evyn,\n\nI noticed you haven't confirmed platform access yet...", "", "", "Subject: ⚡ Quick Fix: AI Platform Access Issues\n\nHi Evyn,\n\nI noticed you haven't confirmed platform access yet. Let's fix this quickly so you're ready for today's 2pm session.\n\n**Common Issues & Solutions:**\n\n🔧 Didn't receive invitation?\n→ Check spam/promotions folder\n→ Search for \"from:openai.com\" or \"from:anthropic.com\"\n\n🔧 Password problems?\n→ Use \"Forgot Password\" on login screen\n→ Create new password (12+ characters)\n\n🔧 Company email not accepted?\n→ Try your personal email temporarily\n→ We'll migrate to company email later\n\n**Need Direct Help?**\n• Slack me: @alex\n• Text: [Number]\n• Zoom office hours: [Link] (drop in anytime)\n\nWe need you platform-ready by 2pm. I'm here to help!\n\nAlex", "Draft"],
  
  ["Week 2", "Status Update", "Medium", "Matt", "Sprint Team", "jameca", new Date(2025, 5, 25), "FLEX", "[Sprint Update] Day 2: RNDC Scorecard Taking Shape!", "Subject: [Sprint Update] Day 2: RNDC Scorecard Taking Shape!\n\nSprint Team,\n\nExcellent progress on Day 2...", "", "", "Subject: [Sprint Update] Day 2: RNDC Scorecard Taking Shape!\n\nSprint Team,\n\nExcellent progress on Day 2! Here's where we stand:\n\n**Completed Today:**\n✅ Data structure defined for RNDC metrics\n✅ Mockups approved by Kait and Joe\n✅ Integration points identified\n✅ Basic automation logic built\n\n**Tomorrow's Focus:**\n• Complete automation rules\n• Build notification system\n• Create executive dashboard view\n• Prepare for Wednesday demo\n\n**Quick Win Alert:**\nThe automated weekly scorecard will save Kait 8-10 hours per week on RNDC reporting. That's 400+ hours annually!\n\nNo roadblocks currently. Demo still on track for Wednesday 2pm.\n\nQuestions? Find me on Slack.\n\nMatt", "Draft"],
  
  ["Week 2", "Training", "High", "Jameca", "Group 1", "", new Date(2025, 5, 25), "HARD", "[Group 1] Your First AI Training Starts Tomorrow - Setup Instructions", "Subject: [Group 1] Your First AI Training Starts Tomorrow - Setup Instructions\n\nHi Operations Team,\n\nExcited for your first AI training tomorrow...", "", "", "Subject: [Group 1] Your First AI Training Starts Tomorrow - Setup Instructions\n\nHi Operations Team,\n\nExcited for your first AI training tomorrow! Let's ensure you're fully prepared:\n\n**Session Details:**\n📅 Thursday, Jan 26 @ 5:00-6:30pm EST\n🔗 Zoom: [Your group's dedicated link]\n👥 Participants: Evyn, Micha, Sara, [New VA]\n\n**Pre-Session Setup (15 min):**\n1. Open ChatGPT Teams in your browser\n2. Click \"New Chat\" and type: \"Hello, I'm learning AI for wine industry operations\"\n3. Take a screenshot of the response\n4. Post screenshot in Slack #unefemme-ai-program\n\n**What to Expect:**\n• Interactive exercises (not lecture!)\n• Wine industry examples throughout\n• Hands-on prompt practice\n• Take-home exercises customized to your role\n\n**Bring:**\n• Laptop (tablets not recommended)\n• One workflow you want to automate\n• Questions - no question is too basic!\n\nCan't wait to start this journey with you!\n\nJameca", "Draft"],
  
  ["Week 2", "Other", "High", "Matt", "All Team", "", new Date(2025, 5, 26), "FLEX", "🎉 SEE IT LIVE: Your RNDC Automation Demo Today at 2pm", "Subject: 🎉 SEE IT LIVE: Your RNDC Automation Demo Today at 2pm\n\nTeam Une Femme,\n\nIn just 3 days, we've built something remarkable...", "", "", "Subject: 🎉 SEE IT LIVE: Your RNDC Automation Demo Today at 2pm\n\nTeam Une Femme,\n\nIn just 3 days, we've built something remarkable. Join us to see YOUR ideas come to life!\n\n**DEMO TODAY: RNDC Scorecard Automation**\n⏰ Time: 5:00pm EST (45 minutes)\n🔗 Zoom: [All-hands link]\n🎯 Must-See: Live automation saving 10+ hours/week\n\n**What You'll See:**\n• Automated RNDC performance tracking\n• Real-time alerts for underperforming regions\n• Executive dashboard with drill-down capabilities\n• One-click report generation\n\n**Why This Matters:**\nThis tool solves the #1 pain point from our survey. If we can build this in 3 days, imagine what's possible in 8 weeks!\n\n**Can't attend?** Recording available, but live Q&A is valuable.\n\nBring your excitement and questions!\n\nMatt", "Draft"],
  
  ["Week 2", "Other", "Medium", "Matt", "All Team", "jameca", new Date(2025, 5, 27), "FLEX", "Week 2 Complete: You've Launched an AI Transformation! 🚀", "Subject: Week 2 Complete: You've Launched an AI Transformation! 🚀\n\nUne Femme Team,\n\nWhat a week! Let's celebrate what you've accomplished...", "", "", "Subject: Week 2 Complete: You've Launched an AI Transformation! 🚀\n\nUne Femme Team,\n\nWhat a week! Let's celebrate what you've accomplished:\n\n**Week 2 Achievements:**\n✅ 100% platform adoption (all 11 users active!)\n✅ RNDC scorecard built and demonstrated\n✅ 2 training groups launched successfully\n✅ 4 executive coaching sessions begun\n✅ First custom GPT prototype created\n\n**By the Numbers:**\n• 10+ hours/week saved with RNDC tool\n• 15 AI prompts mastered by team\n• 3 workflow automations identified\n• 100% session attendance rate\n\n**Coming in Week 3:**\n• Full assessment results presentation\n• Module 2: Advanced prompt engineering\n• Executive GPT customization\n• Calabrai platform launch\n\n**Weekend Homework:**\nPractice what you learned! Try using AI for one work task and share your experience in Slack.\n\nThank you for your energy, openness, and commitment. We're just getting started!\n\nHave a wonderful weekend,\n\nMatt", "Draft"],
  
  // WEEKS 3-7: ONGOING PROGRAM EMAILS (UF-030 to UF-097)
  ["Weeks 3-7", "Training", "Medium", "Jameca", "Group 1", "", new Date(2025, 5, 30), "HARD", "[Reminder] AI Training Tomorrow: Module 2 - Advanced Prompting", "Subject: [Reminder] AI Training Tomorrow: Module 2 - Advanced Prompting\n\nHi Group 1,\n\nReminder: your next AI training is tomorrow...", "", "", "Subject: [Reminder] AI Training Tomorrow: Module 2 - Advanced Prompting\n\nHi Group 1,\n\nReminder: your next AI training is tomorrow!\n\n**Topic: Module 2 - Advanced Prompting**\nWe'll cover:\n• The RARE framework (Role, Audience, Result, Example)\n• Chain-of-thought prompting for complex tasks\n• Zero-shot vs. few-shot prompting\n\n📅 Thursday @ 5:00-6:30pm EST\n🔗 Zoom: [Your group's dedicated link]\n\n**Pre-Work (15 min):**\n1. Read attached PDF: \"5 Levels of Prompting\"\n2. Find one email you wrote this week\n3. Come ready to rewrite it using the RARE framework\n\n**Homework Due:**\nPlease submit your Module 1 homework (3 prompts) by EOD today so Aaron has time to review.\n\nSee you tomorrow!\nJameca", "Draft"],
  
  ["Weeks 3-7", "Training", "Medium", "Jameca", "Group 2", "", new Date(2025, 5, 31), "HARD", "[Reminder] AI Training Tomorrow: Module 2 - Advanced Prompting", "Subject: [Reminder] AI Training Tomorrow: Module 2 - Advanced Prompting\n\nHi Group 2,\n\nReminder: your next AI training is tomorrow...", "", "", "Subject: [Reminder] AI Training Tomorrow: Module 2 - Advanced Prompting\n\nHi Group 2,\n\nReminder: your next AI training is tomorrow!\n\n**Topic: Module 2 - Advanced Prompting**\nWe'll cover:\n• The RARE framework (Role, Audience, Result, Example)\n• Chain-of-thought prompting for complex tasks\n• Zero-shot vs. few-shot prompting\n\n📅 Friday @ 1:00-2:30pm EST\n🔗 Zoom: [Your group's dedicated link]\n\n**Pre-Work (15 min):**\n1. Read attached PDF: \"5 Levels of Prompting\"\n2. Find one email you wrote this week\n3. Come ready to rewrite it using the RARE framework\n\n**Homework Due:**\nPlease submit your Module 1 homework (3 prompts) by EOD today so Aaron has time to review.\n\nSee you tomorrow!\nJameca", "Draft"],
  
  ["Weeks 3-7", "Survey", "Medium", "Aaron", "Sara Soares", "", new Date(2025, 6, 2), "FLEX", "✅ Feedback on Your Module 1 Prompts", "Subject: ✅ Feedback on Your Module 1 Prompts\n\nHi Sara,\n\nThanks for submitting your Module 1 homework...", "", "", "Subject: ✅ Feedback on Your Module 1 Prompts\n\nHi Sara,\n\nThanks for submitting your Module 1 homework. Your prompts for financial forecasting were excellent!\n\n**Feedback & Suggestions:**\n\n**Prompt 1: \"Forecast Q3 revenue\"**\n• **What Worked:** Clear and direct.\n• **Suggestion:** Add more context for better results. Try: \"Acting as a financial analyst for a fast-growing wine company, forecast Q3 revenue based on the attached sales data (Q1-Q2 2024), considering a 15% summer seasonal lift and a new partnership with Delta launching in July.\"\n\n**Prompt 2: \"Analyze budget variance\"**\n• **What Worked:** Good use of a specific term.\n• **Suggestion:** Specify the format for the output. Try adding: \"...present the results in a markdown table with columns for Budget, Actual, Variance $, and Variance %.\"\n\n**Prompt 3: \"Explain compliance costs\"**\n• **What Worked:** Great, open-ended question for exploration.\n• **Suggestion:** To make it more actionable, add a role. \"Explain the main drivers of compliance costs to a new board member who is unfamiliar with the wine industry.\"\n\nOverall, fantastic start. You're already thinking like a prompt engineer!\n\nLet me know if you have any questions. See you in the next session!\n\nBest,\nAaron", "Draft"],
  
  ["Weeks 3-7", "Other", "Medium", "Matt", "Jen Pelka", "", new Date(2025, 6, 5), "FLEX", "AI Executive Coaching: Building Your \"Fun Brand\" Assistant", "Subject: AI Executive Coaching: Building Your \"Fun Brand\" Assistant\n\nHi Jen,\n\nNow that the team is trained on the basics...", "", "", "Subject: AI Executive Coaching: Building Your \"Fun Brand\" Assistant\n\nHi Jen,\n\nNow that the team is trained on the basics, it's time for your dedicated 1-on-1 coaching. Let's build your personal AI assistant to accelerate the \"serious to fun\" brand evolution.\n\n**Book Your Weekly Coaching Sessions:**\n\n🗓️ Schedule your recurring slot: [Calendly Link]\n\nAvailable times (EST):\n• Tuesday-Thursday 2:00-5:00pm EST\n• 45-minute weekly sessions\n• Choose the same time slot for consistency\n\n**This Week's Focus:**\nDesigning your \"Brand Evolution GPT\" that helps you:\n• Generate \"fun\" messaging variations\n• Test brand voice transitions\n• Create content that bridges serious wine expertise with approachable personality\n\n**Prep for Our Session:**\nBring 2-3 recent pieces of Une Femme communications (emails, social posts, etc.) that feel \"too serious\" and need a \"fun\" makeover.\n\nLooking forward to building something transformative for your brand vision!\n\nBest,\nMatt", "Draft"],
  
  ["Weeks 3-7", "Survey", "Medium", "Jameca", "All Team", "", new Date(2025, 6, 14), "FLEX", "Quick Pulse Check: How's Your AI Journey Going? (3 min survey)", "Subject: Quick Pulse Check: How's Your AI Journey Going? (3 min survey)\n\nHi Team,\n\nWe're halfway through! Let's ensure the program is meeting your needs...", "", "", "Subject: Quick Pulse Check: How's Your AI Journey Going? (3 min survey)\n\nHi Team,\n\nWe're halfway through! Let's ensure the program is meeting your needs.\n\n**Take 3-Minute Pulse Check:** [TypeForm Link]\n\n**We're Asking About:**\n• What's working well\n• Where you need more support\n• Topics for office hours\n• Success stories to share\n\nYour feedback directly shapes Weeks 5-8.\n\n**Incentive:** Complete by Friday for entry into wine gift basket drawing! 🍷\n\nThanks for helping us optimize your experience.\n\nJameca", "Draft"],
  
  ["Weeks 3-7", "Platform Setup", "High", "Alex", "All Team", "", new Date(2025, 6, 20), "HARD", "🎯 NEW: Your AI Prompt Library is Live (Calabrai Platform)", "Subject: 🎯 NEW: Your AI Prompt Library is Live (Calabrai Platform)\n\nTeam,\n\nGame-changer alert! Your dedicated AI prompt platform is ready...", "", "", "Subject: 🎯 NEW: Your AI Prompt Library is Live (Calabrai Platform)\n\nTeam,\n\nGame-changer alert! Your dedicated AI prompt platform is ready.\n\n**Introducing Calabrai for Une Femme:**\n\nWhat it does:\n• Saves your successful prompts\n• Shares prompts across the team\n• Includes Une Femme-specific context\n• Tracks which prompts deliver results\n\n**Access Now:**\n🔗 URL: unefemme.calabrai.com\n👤 Username: Your Une Femme email\n🔐 Temp Password: ChangeMeNow2024!\n\n**15-Minute Quick Start Sessions:**\n\n🗓️ Book your training: [Calendly Link]\n\nAvailable slots (EST):\n• Tuesday 5:00pm EST\n• Wednesday 1:00pm EST\n• Thursday 6:00pm EST\n\n**Why This Matters:**\nStop recreating prompts! Build on each other's successes. Kait's already saved 3 hours using Sam's sales prompts.\n\nQuestions? I'm your Calabrai champion.\n\nAlex", "Draft"],
  
  ["Weeks 3-7", "Other", "Low", "Jameca", "All Team", "", new Date(2025, 6, 27), "FLEX", "🌟 AI WIN: How Sara Saved 6 Hours on Financial Forecasting", "Subject: 🌟 AI WIN: How Sara Saved 6 Hours on Financial Forecasting\n\nTeam,\n\nLet's celebrate this week's AI success story...", "", "", "Subject: 🌟 AI WIN: How Sara Saved 6 Hours on Financial Forecasting\n\nTeam,\n\nLet's celebrate this week's AI success story!\n\n**Sara's Breakthrough:**\nChallenge: Monthly financial forecasting took 8 hours of manual Excel work\nSolution: Created AI prompt to analyze sales patterns and generate forecast\nResult: Now completes in 2 hours with 99.9% accuracy!\n\n**Sara's Magic Prompt:**\n\"Analyze the attached Une Femme sales data. Identify seasonal patterns, growth trends, and anomalies. Generate a 3-month forecast with confidence intervals. Format as Excel-ready table with assumptions listed.\"\n\n**Try It Yourself:**\nThis prompt is now saved in Calabrai under \"Financial Forecasting\"\n\n**Your Turn:**\nWhat's your AI win this week? Share in Slack for next week's spotlight!\n\nKeep innovating!\n\nJameca", "Draft"],
  
  // WEEK 8: PROGRAM WRAP-UP EMAILS (UF-106 to UF-113)
  ["Week 8", "Other", "Medium", "Matt", "All Team", "", new Date(2025, 7, 4), "FLEX", "Final Week: Let's Celebrate Your AI Transformation! 🎉", "Subject: Final Week: Let's Celebrate Your AI Transformation! 🎉\n\nUne Femme AI Pioneers,\n\nCan you believe it's Week 8...", "", "", "Subject: Final Week: Let's Celebrate Your AI Transformation! 🎉\n\nUne Femme AI Pioneers,\n\nCan you believe it's Week 8? You've built incredible momentum in just 7 weeks!\n\n**This Week's Schedule:**\n• Mon-Tue: Final module sessions\n• Wednesday: Skills assessment (earn your certificate!)\n• Thursday: Executive results presentation\n• Friday: Celebration & Phase 2 planning\n\n**Your Transformation by Numbers:**\n✅ 40+ hours of productivity gained\n✅ 3 automated workflows deployed\n✅ 15+ reusable prompts created\n✅ 100% team AI adoption\n\n**Reflection Question:**\nWhat's the biggest change in how you approach your work now vs. 8 weeks ago?\n\nShare your thoughts in Slack - we're compiling transformation stories!\n\nLet's make this final week memorable.\n\nMatt", "Draft"],
  
  ["Week 8", "Other", "High", "Jameca", "All Participants", "", new Date(2025, 7, 6), "HARD", "[Action Required] Complete Your AI Skills Assessment - Earn Your Certificate!", "Subject: [Action Required] Complete Your AI Skills Assessment - Earn Your Certificate!\n\nHi Team,\n\nTime to showcase what you've learned and earn your certificate...", "", "", "Subject: [Action Required] Complete Your AI Skills Assessment - Earn Your Certificate!\n\nHi Team,\n\nTime to showcase what you've learned and earn your certificate!\n\n**AI Skills Assessment**\n📅 Available: Now through Wednesday 8pm EST\n⏱️ Time Required: 45 minutes\n🔗 Access: [Assessment Link]\n🏆 Pass Rate: 80% (you can retake if needed)\n\n**What's Covered:**\n• Prompt engineering principles\n• Wine industry AI applications\n• Tool selection and usage\n• Ethical considerations\n• ROI calculation\n\n**Tips for Success:**\n• Review your module notes\n• Have ChatGPT/Claude open for practical exercises\n• Use your Calabrai saved prompts\n\n**Why Complete It?**\n✓ Receive Une Femme AI Pioneer Certificate\n✓ Validate your new skills\n✓ Add to LinkedIn profile\n✓ Qualify for Phase 2 advanced training\n\nQuestions? I'm here to help you succeed!\n\nJameca", "Draft"],
  
  ["Week 8", "Other", "High", "Matt", "Executives", "", new Date(2025, 7, 7), "FLEX", "[Executives + VIPs] AI Program Results: ROI Revealed", "Subject: [Executives + VIPs] AI Program Results: ROI Revealed\n\nExecutive Team,\n\nReady to see the remarkable ROI from your AI investment...", "", "", "Subject: [Executives + VIPs] AI Program Results: ROI Revealed\n\nExecutive Team,\n\nReady to see the remarkable ROI from your AI investment?\n\n**AI Program Results Presentation**\n📅 Thursday, August 7 @ 1:00pm EST\n⏱️ Duration: 90 minutes\n🔗 Zoom: [Executive meeting link]\n\n**Agenda:**\n1. Performance metrics vs. objectives (Sam's KPIs)\n2. Demonstrated ROI and productivity gains\n3. Live demonstrations of solutions\n4. Team transformation stories\n5. Phase 2 recommendations\n6. Q&A and strategic planning\n\n**Spoiler Alert:**\nWe've exceeded every target metric, including 40+ hours/week saved across the team.\n\n**Pre-Read:**\nExecutive summary arriving Wednesday evening.\n\nThis is your victory lap - don't miss it!\n\nMatt", "Draft"],
  
  ["Week 8", "Other", "Medium", "Matt", "All Team", "jameca", new Date(2025, 7, 8), "FLEX", "🥂 Celebrate: Une Femme AI Graduation Party!", "Subject: 🥂 Celebrate: Une Femme AI Graduation Party!\n\nAmazing Une Femme AI Pioneers!\n\nYou did it! Let's celebrate your transformation together...", "", "", "Subject: 🥂 Celebrate: Une Femme AI Graduation Party!\n\nAmazing Une Femme AI Pioneers!\n\nYou did it! Let's celebrate your transformation together.\n\n**AI Program Graduation Celebration**\n📅 Friday, August 8 @ 6:00pm EST\n⏱️ Duration: 60 minutes of fun!\n🔗 Zoom: [Celebration link]\n🍷 BYOB: Bring your favorite Une Femme wine!\n\n**Celebration Agenda:**\n• Success story sharing (volunteers welcome!)\n• Certificate presentations\n• Surprise guest appearance 👀\n• Phase 2 exclusive preview\n• Virtual toast to your success\n\n**Special Moments:**\n- Kait demos how she's saving 10+ hours/week\n- Sara shares her 99.9% accurate AI forecasting\n- Custom GPT showcase\n- Team awards and recognition\n\nDress code: Business casual + celebration mode!\n\nCan't wait to celebrate with you!\n\nMatt & Jameca", "Draft"],
  
  ["Week 8", "Other", "High", "Jameca", "All Team", "", new Date(2025, 7, 9), "FLEX", "🎓 Your Une Femme AI Transformation Toolkit - Everything You Need", "Subject: 🎓 Your Une Femme AI Transformation Toolkit - Everything You Need\n\nCongratulations, Une Femme AI Pioneer!\n\nYou've completed the transformation program...", "", "", "Subject: 🎓 Your Une Femme AI Transformation Toolkit - Everything You Need\n\nCongratulations, Une Femme AI Pioneer!\n\nYou've completed the transformation program. Here's your complete toolkit for continued success:\n\n**🎓 Your Certificate**\nAttached: Une Femme AI Pioneer Certificate\nAdd to LinkedIn: \"AI Transformation Program - Happy Robots\"\n\n**📚 Your Resource Library**\nAccess link: [Une Femme AI Portal]\nIncludes:\n• All 6 module recordings\n• 50+ prompt templates\n• Wine industry AI playbook\n• Custom GPT gallery\n• ROI calculator\n\n**🔧 Continued Access**\n✓ Calabrai platform: Lifetime access\n✓ Slack community: Remains active\n✓ Monthly office hours: Ongoing\n✓ Happy Robots newsletter: Auto-subscribed\n\n**📊 Your Personal Impact**\n[Personalized metrics based on role]\nExample: \"Kait - you've saved 80+ hours and improved RNDC compliance by 35%\"\n\n**🚀 What's Next?**\n• Phase 2 proposal in your inbox Monday\n• Monthly AI advances newsletter\n• Alumni network launching April\n\n**One Final Request:**\nWould you write a brief testimonial about your experience? Your story helps other wine brands see what's possible.\n\nThank you for your trust, energy, and innovation. You've proven that wine industry excellence and AI innovation go hand-in-hand.\n\nStay in touch!\n\nJameca\n\nP.S. - You're always welcome to reach out with questions. Once Happy Robots family, always family!", "Draft"],
  
  // POST-PROGRAM EMAILS (UF-114+)
  ["Post-Program", "Other", "Medium", "Matt", "Zach Pelka", "jen", new Date(2025, 7, 11), "FLEX", "Ready for More? Une Femme AI Phase 2 Preview", "Subject: Ready for More? Une Femme AI Phase 2 Preview\n\nHi Zach,\n\nAfter seeing your team's incredible Week 8 results...", "", "", "Subject: Ready for More? Une Femme AI Phase 2 Preview\n\nHi Zach,\n\nAfter seeing your team's incredible Week 8 results, I'm excited to share what Phase 2 could unlock for Une Femme.\n\n**Phase 2: Contextualize & Scale (12 weeks)**\n\nBuilding on your foundation, we would:\n• Create Une Femme's AI context engine\n• Develop department-specific AI workflows\n• Build predictive models for 600k case scaling\n• Implement AI governance framework\n• Train internal AI champions\n\n**Expected Outcomes:**\n• Additional 100+ hours/week saved\n• Predictive accuracy for demand planning\n• Automated compliance across 50 states\n• AI-powered innovation pipeline\n\n**Investment:** [Phase 2 pricing]\n**Timeline:** September - November 2025\n\nFull proposal coming Monday with detailed ROI projections.\n\nWant to discuss over a glass of Une Femme? I'm free Tuesday afternoon.\n\nBest,\nMatt", "Draft"]
];

sheet.getRange("B2:O47").setValues(uneFemmeEmails);

// NOW set up data validations (after data is populated)
const configSheet = ss.getSheetByName("Configuration");

// Phase dropdown - start from row 48 to avoid overwriting pre-populated data
sheet.getRange("B48:B100").setDataValidation(
  SpreadsheetApp.newDataValidation()
    .setAllowInvalid(false)
    .requireValueInRange(configSheet.getRange("A8:A12"))
    .build()
);

// Category dropdown - start from row 48 to avoid overwriting pre-populated data
sheet.getRange("C48:C100").setDataValidation(
  SpreadsheetApp.newDataValidation()
    .setAllowInvalid(false)
    .requireValueInRange(configSheet.getRange("E8:E16"))
    .build()
);

// Priority dropdown - start from row 48 to avoid overwriting pre-populated data
sheet.getRange("D48:D100").setDataValidation(
  SpreadsheetApp.newDataValidation()
    .setAllowInvalid(false)
    .requireValueInList(["High", "Medium", "Low"])
    .build()
);

// From dropdown - allow multiple selections (comma-separated)
sheet.getRange("E48:E100").setDataValidation(
  SpreadsheetApp.newDataValidation()
    .setAllowInvalid(true)
    .requireValueInRange(configSheet.getRange("I8:I15"))
    .setHelpText("Select one or multiple team members. For multiple, use format: 'Matt, Danielle, Alex'")
    .build()
);

// Status dropdown - start from row 48 to avoid overwriting pre-populated data
sheet.getRange("O48:O100").setDataValidation(
  SpreadsheetApp.newDataValidation()
    .setAllowInvalid(false)
    .requireValueInList(["Draft", "Ready", "Sent", "Confirmed", "No Response", "Cancelled"])
    .build()
);

// Flexibility dropdown - start from row 48 to avoid overwriting pre-populated data
sheet.getRange("I48:I100").setDataValidation(
  SpreadsheetApp.newDataValidation()
    .setAllowInvalid(false)
    .requireValueInList(["HARD", "FLEX", "ASAP"])
    .build()
);

// Y/N dropdowns - start from row 48 to avoid overwriting pre-populated data
sheet.getRange("Q48:Q100").setDataValidation(
  SpreadsheetApp.newDataValidation()
    .setAllowInvalid(false)
    .requireValueInList(["Y", "N"])
    .build()
);

sheet.getRange("T48:T100").setDataValidation(
  SpreadsheetApp.newDataValidation()
    .setAllowInvalid(false)
    .requireValueInList(["Y", "N"])
    .build()
);

// Conditional formatting
addConditionalFormatting(sheet);

// Add visual enhancements
enhanceEmailTrackerVisuals(sheet);